spring:
  application:
    name: backend

server:
  port: 8080
  forward-headers-strategy: framework

management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

logging:
  level:
    org.springframework: INFO
