spring:
  application:
    name: backend

server:
  port: 8080
  forward-headers-strategy: framework

management:
  server:
    port: 8081
    address: 127.0.0.1
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework: INFO
