name: CD - Deploy 2025-08-jwt-auth

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types: ["completed"]

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script_stop: true
          script: |
            set -euo pipefail
            set -x

            docker --version
            docker compose version || true

            cd /srv/docker/labs/2025-08-jwt-auth/deploy || (echo "deploy 디렉터리 없음"; exit 1)
            test -f docker-compose.yml || (echo "docker-compose.yml 없음"; ls -la; exit 1)
            test -f .env || (echo ".env 없음 (REGISTRY/PROJECT_NAME 필요)"; exit 1)
            echo "===== .env 내용(민감값 제외) ====="
            grep -E '^(REGISTRY|PROJECT_NAME)=' .env || true

            # GHCR 로그인
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            # <-- 여기서 TAG 설정/내보내기
            export TAG=${{ github.event.workflow_run.head_sha }}

            # compose 유효성 확인(렌더 결과에 TAG 반영됐는지 확인)
            docker compose config >/tmp/compose.rendered.yml
            head -n 60 /tmp/compose.rendered.yml || true

            # 이미지 풀 (리트라이)
            for i in 1 2 3; do
              if docker compose pull; then break; fi
              echo "pull retry $i"; sleep 3
            done

            # 기동
            docker compose up -d --remove-orphans

            docker compose ps
            docker compose ls || true

            chmod +x ./scripts/smoke_backend.sh ./scripts/smoke_frontend.sh
            ./scripts/smoke_backend.sh
            ./scripts/smoke_frontend.sh

            docker logout ghcr.io
