name: CD - Deploy 2025-08-jwt-auth

on:
  workflow_run:
    workflows: ["CI - Build & Push"]
    types: [ "completed" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script_stop: true
          script: |
            set -euo pipefail
            cd /srv/docker/labs/2025-08-jwt-auth/deploy
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            for i in {1..3}; do docker compose pull && break || (echo "pull retry $i" && sleep 3); done
            TAG=${{ github.event.workflow_run.head_sha }} docker compose up -d --remove-orphans
            bash ./scripts/smoke_backend.sh
            bash ./scripts/smoke_frontend.sh
            docker logout ghcr.io
